site_name: 'Convert-Pheno Documentation'
site_description: 'Convert-Pheno Toolbox Documentation'
site_author: 'Manuel Rueda, PhD'
copyright: '&copy; Copyright 2022-2023, Manuel Rueda, CNAG'
repo_name: 'Convert-Pheno'
repo_url: https://github.com/mrueda/convert-pheno
edit_uri: edit/main/docs/

extra_css: [css/theme_overrides.css]
extra_javascript: [js/theme_overrides.js]

plugins:
  - search
  - macros
#  - external-markdown
  - mermaid2:
      arguments:
        startOnLoad: true

markdown_extensions:
    - toc:
        toc_depth: 2-3
        permalink: true
    - admonition
    - attr_list
    - footnotes
    - md_in_html
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.details
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - pymdownx.saneheaders
    - pymdownx.magiclink:
        hide_protocol: true
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.tasklist:
        custom_checkbox: true
    - tables
    - mdx_gh_links:
        user: ga4gh-beacon
        repo: beacon-v2
    - pymdownx.emoji:
          emoji_index: !!python/name:materialx.emoji.twemoji
          emoji_generator: !!python/name:materialx.emoji.to_svg
    - pymdownx.superfences:
        custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:mermaid2.fence_mermaid   
    - pymdownx.snippets:
        base_path: docs

nav:
  - Introduction:
      - What is Convert-Pheno?: what-is-convert-pheno.md
      - Supported formats: supported-formats.md
  - 'Download & Installation': download-and-installation.md
  - Use:
      - As a command-line interface: use-as-a-command-line-interface.md
      - As a module: use-as-a-module.md
      - As an API: use-as-an-api.md
      - Web App User interface: https://cnag-biomedical-informatics.github.io/convert-pheno-ui/
  - Formats accepted:
      - Beacon v2 Models (BFF): bff.md
      - Phenopacket v2 (PXF): pxf.md
      - REDCap: redcap.md
      - OMOP-CDM: omop-cdm.md
      - CDISC-ODM: cdisc-odm.md
  - Technical details:
      - Implementation: implementation.md
      - Mapping steps: mapping-steps.md
      - Mapping tables:
        - OMOP to BFF: omop2bff.md
        - PXF to BFF: pxf2bff.md
        - BFF to PXF: bff2pxf.md 
  - Help:
      - Tutorial: tutorial.md
      - Google colab: https://colab.research.google.com/drive/1T6F3bLwfZyiYKD6fl1CIxs9vG068RHQ6
      - FAQs: faq.md
      - Future plans: future-plans.md
  - About:
      - About: about.md
      - Citation: citation.md
    # - Download PDF: pdf/beacon.pdf

theme:
  name: material
  #custom_dir: overrides
  palette:
  - media: '(prefers-color-scheme: dark)'
    scheme: default
    primary: blue grey
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  - media: '(prefers-color-scheme: light)'
    scheme: slate
    primary: blue grey
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  logo: img/CP-logo-grey.png
  icon:
      repo: fontawesome/brands/github-alt 
  features:
        - content.tabs.link
        - search.highlight
        - search.share
        # - navigation.instant # otherwise blocks rendering of mermaid on page load
        - navigation.tracking
        - navigation.sections
        - toc.integrate

# Options
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/mrueda

# https://pypi.org/project/mkdocs-with-pdf/ for more PDF configuration ...
