import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const docsSiteDir = path.resolve(path.dirname(__filename), '..');
const repoRoot = path.resolve(docsSiteDir, '..');

const generatedHeader = `<!--
Generated from repository README content.
Do not edit this file directly; edit the source README and run:
  npm --prefix docs-site run prebuild
-->
`;

const pages = [
  {
    source: path.join(repoRoot, 'non-containerized', 'README.md'),
    target: path.join(docsSiteDir, 'docs', 'download-and-installation', 'non-containerized.md'),
    title: 'Non-Containerized Installation',
    sidebarLabel: 'Non-Containerized',
  },
  {
    source: path.join(repoRoot, 'docker', 'README.md'),
    target: path.join(docsSiteDir, 'docs', 'download-and-installation', 'docker-based.md'),
    title: 'Docker Installation',
    sidebarLabel: 'Docker',
  },
];

function stripFirstHeading(markdown) {
  return markdown.replace(/^# .+\n+/, '');
}

function normalizeForMdx(markdown) {
  return markdown.replace(/<((?:https?:\/\/|mailto:)[^>\s]+)>/g, '[$1]($1)');
}

function frontMatter(page) {
  return `---\ntitle: ${page.title}\nsidebar_label: ${page.sidebarLabel}\n---\n\n`;
}

for (const page of pages) {
  const source = fs.readFileSync(page.source, 'utf8');
  const body = normalizeForMdx(stripFirstHeading(source)).trimEnd();
  const output = `${frontMatter(page)}${generatedHeader}\n# ${page.title}\n\n${body}\n`;

  fs.mkdirSync(path.dirname(page.target), {recursive: true});
  fs.writeFileSync(page.target, output);
}
