---
  diseases:
    fields: [Inflammatory Bowel Disease]
    dict:
      ageOfOnset: age_first_diagnosis
      familyHistory: family_history
  ethnicity: ethnicity
  exposures: 
    fields: [alcohol,smoking,cigarettes_days,cigarettes_years,packyears,smoking_quit]
  geographicOrigin: null
  id: null
  info:
   fields: [study_id,dob,diet,redcap_event_name,age,first_name,last_name,consent,consent_date,consent_noneu,consent_devices,consent_recontact,consent_week2_endo,education,zipcode,consents_and_demographics_complete]
   dict:
     studyId: study_id
  interventionsOrProcedures: 
    fields: [surgery_details___1,surgery_details___2,surgery_details___3,surgery_details___4,surgery_details___5,surgery_details___6,surgery_details___7,surgery_details___8,surgery_details___99,endoscopy_performed,intestinal_surgery,partial_mayo,complete_mayo,prev_endosc_dilatation]
  karyotypicSex: null
  measures: 
    fields: [leucocytes,hemoglobin,hematokrit,mcv,mhc,thrombocytes,neutrophils,lymphocytes,eosinophils,creatinine,gfr,bilirubin,gpt,ggt,lipase,crp,iron,il6,calprotectin,nancy_index_acute,nancy_index_chronic,nancy_index_ulceration,endo_mayo]
  pedigrees: null
  phenotypicFeatures: 
    fields: [comorb_asthma,comorb_copd,comorb_ms,comorb_sle,comorb_ra,comorb_pso,comorb_ad,comorb_cancer,comorb_cancer_specified,comorb_hypertension,comorb_diabetes,comorb_lipids,comorb_stroke,comorb_other_ai,comorb_other_ai_specified,immunodeficiency,rectal_bleeding]
  sex: sex
  treatments:
    fields: [budesonide,prednisolone,asa,aza,mtx,mp]
    dict:
      aza: azathioprine
      asa: aspirin 
      mtx: methotrexate
      mp: mercaptopurine
    routes: [oral,rectal]
