name: Conda build from CPAN
 
on:
     workflow_dispatch
#    push:
#        branches: 'main'
#    pull_request:
#        branches: '*'
#    schedule:
#        - cron: '42 5 * * 0'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['macos-latest']
        perl: [ '5.32']
    name: Perl ${{ matrix.perl }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Run tests (no coverage)
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: perl -V
      - run: cpanm Convert::Pheno
      - run: prove -l t
