name: Docker build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
   runs-on: ubuntu-latest
   container: ./Dockerfile 
   steps:
     - uses: actions/checkout@v2
     - name: Build Docker image 
       run: docker build -t cnag/convert-pheno:latest .
