name: Docker build and push

on:
   workflow_dispatch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2

     - name: Build Docker image 
       run: docker build -t manuelrueda/convert-pheno:latest .

     - name: Login to Docker Hub
       uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}

     - name: Push to Docker Hub
       run: docker image push manuelrueda/convert-pheno:latest
