name: Documentation
on:
  workflow_dispatch
# push:
#   branches:
#     - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: pip install mkdocs-macros-plugin
      # - run: pip install mkdocs-with-pdf
      - run: pip install mkdocs-mermaid2-plugin
      - run: pip install pymdown-extensions
      - run: pip install mdx_gh_links
      - run: mkdocs gh-deploy --force
